# Site settings
title: Yupu's blog
header-img: img/post-bg-01.jpg  #img/bg-index.jpg
email: dongyupu@foxmail.com
description: "Dream big, work smart, deliver fast!Software to plan, collaborate, code, and service. Built for teams."
baseurl: ""
url: "https://dongyupu.github.io/"
#twitter_username: 741375879
github_username:  dongyupu
#facebook_username:  dong.yupu.7
#weibo_username: dongyupu1988
#zhihu_username: dongyupu

#add baidu analyze
analytics:
    provider: custom

# Build settings
markdown: kramdown
highlighter: rouge  #pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
